# Enable EC11 driver debug logs for wired diagnosis.
CONFIG_SENSOR_LOG_LEVEL_DBG=y

# Use the patched EC11 driver for more reliable quadrature decoding.
CONFIG_EC11=n
CONFIG_ZMK_PATCH_EC11=y
CONFIG_ZMK_PATCH_EC11_TRIGGER_GLOBAL_THREAD=y
